name: Terraform test

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
  
on:
  workflow_dispatch

jobs:
  terraform_test:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: check
        run: ls -la

      - name: terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.4.2
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
            
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
