name: Terraform test
 
on:
  workflow_dispatch:
    inputs:
      resource_group:
      evhns:

jobs:
  terraform:
    permissions:
      contents: read
      id-token: write
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Curl
      run: sudo apt update && sudo apt upgrade -y && sudo apt install -y net-tools

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          IP=$(curl ifconfig.io)
          echo $IP
